language: node_js
node_js:
  - 8
  - 10
  - node
cache:
  yarn: true
  directories:
    - .npm
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
  - export PATH="$HOME/.yarn/bin:$PATH"
install: true
script:
  - 'if [ $TEST_SUITE = "basic" ]; then yarn build; fi'
env:
  matrix:
    - TEST_SUITE=basic
