language: node_js
node_js:
  - 8
  - 10
  - node
cache:
  yarn: true
  directories:
    - .npm
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - 'if [ $TEST_SUITE = "build:basic" ]; then yarn build:basic; fi'
  - 'if [ $TEST_SUITE = "build:static-site" ]; then yarn build:static-site; fi'
  - 'if [ $TEST_SUITE = "build:spa-angular" ]; then yarn build:spa-angular; fi'
  - 'if [ $TEST_SUITE = "test:init" ]; then yarn test:init; fi'
env:
  matrix:
    - TEST_SUITE=build:basic
    - TEST_SUITE=build:static-site
    - TEST_SUITE=build:spa-angular
    - TEST_SUITE=test:init
